version: "3"
services:
  url-shortener:
    image: 'leetcode-redirect:latest'
    container_name: leetcode-redirect
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
networks:
  default:
    name: nginx-proxy-manager
    external: true
